In [ ]:
#t.varshini


In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
array = np.array([1,2,3,4,5])
print("array:")
print(array)

array:
[1 2 3 4 5]


In [5]:
print(" shape of the array:")
print(array.shape)


 shape of the array:
(5,)


AttributeError: module 'pandas' has no attribute 'series'

In [8]:
abc = pd.Series([10,20,30,40,50])
print("series:")
print(abc)

series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [9]:
onearr = ([1,2,3,4,5,6,7,8,9,10])
print("one dimensional array:")
print(onearr)

one dimensional array:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
mularr = ([[10,20,30,40,50],[1,2,3,4,5],[6,7,8,9,10]])
print("multi dimensional array:")
print(mularr)

multi dimensional array:
[[10, 20, 30, 40, 50], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [11]:
z = np.zeros((4,5))
print(z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
z1=np.ones((5,4))
print(z1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
